# Generated by Django 2.2.14 on 2020-08-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='jobTitle1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
