# Generated by Django 2.2.14 on 2020-08-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200829_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='jobTitle2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='jobTitle3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='jobTitle4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
