# Generated by Django 2.2.14 on 2020-08-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200829_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='jobTitle1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='jobTitle2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='jobTitle3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='jobTitle4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
