# Generated by Django 2.2.14 on 2020-08-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200830_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='start_year',
        ),
        migrations.AddField(
            model_name='resume',
            name='end_month1',
            field=models.IntegerField(choices=[('', ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=8),
        ),
        migrations.AddField(
            model_name='resume',
            name='end_month2',
            field=models.IntegerField(choices=[('', ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=8),
        ),
        migrations.AddField(
            model_name='resume',
            name='end_year1',
            field=models.IntegerField(choices=[('', ''), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020),
        ),
        migrations.AddField(
            model_name='resume',
            name='end_year2',
            field=models.IntegerField(choices=[('', ''), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020),
        ),
        migrations.AddField(
            model_name='resume',
            name='start_month1',
            field=models.IntegerField(choices=[('', ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=8),
        ),
        migrations.AddField(
            model_name='resume',
            name='start_month2',
            field=models.IntegerField(choices=[('', ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=8),
        ),
        migrations.AddField(
            model_name='resume',
            name='start_year1',
            field=models.IntegerField(choices=[('', ''), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020),
        ),
        migrations.AddField(
            model_name='resume',
            name='start_year2',
            field=models.IntegerField(choices=[('', ''), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020),
        ),
        migrations.AlterField(
            model_name='resume',
            name='jobTitle1',
            field=models.CharField(max_length=100),
        ),
    ]
