# Generated by Django 2.2.14 on 2020-08-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200830_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='jobTitle3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='jobTitle4',
        ),
        migrations.AddField(
            model_name='resume',
            name='job_description1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='job_description2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
