# Generated by Django 2.2.14 on 2020-08-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200831_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skillField1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='skillField2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='skillField3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
