# Generated by Django 2.2.14 on 2020-08-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200831_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skillField4',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
